
on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        service:
          - frontend
          - backend
          - vidbackend/Pulse_Backend_Video/pulse/backendvid

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.service }} Docker image
        run: |
          IMAGE_NAME=${{ matrix.service }}
          IMAGE_TAG=$(date +%s)
          DOCKERFILE_PATH=${{ matrix.service }}/Dockerfile
          docker build ${{ matrix.service }} --file $DOCKERFILE_PATH --tag $IMAGE_NAME:$IMAGE_TAG
