name: Docker CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: frontend
            image: frontend
          - context: backend
            image: backend
          - context: vidbackend/Pulse_Backend_Video/pulse/backendvid
            image: backendvid

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.image }} Docker image
        run: |
          IMAGE_NAME=${{ matrix.image }}
          IMAGE_TAG=$(date +%s)
          docker build ${{ matrix.context }} --file ${{ matrix.context }}/Dockerfile --tag $IMAGE_NAME:$IMAGE_TAG
